CBVProject/CBVProject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('cbvapp.urls'))
]

CBVProject/cbvapp/urls.py
from django.urls import path
from .views import *

app_name='cbvapp'
urlpatterns = [
	path('',HomePage.as_view()),
	path('retrivedata/',StudentListView.as_view(),name='retrivedata'),
	path('studentform/',StudentFormView.as_view(),name='studentform'),
	path('update/<int:pk>/',StudentUpdateView.as_view(),name='update'),
	path('delete/<int:pk>/',StudentDeleteView.as_view(),name='delete')
]

CBVProject/cbvapp/models.py
from django.db import models

# Create your models here.

class Student(models.Model):
	rollno=models.IntegerField(default=False)
	name=models.CharField(max_length=100)
	email=models.EmailField(max_length=1000)
	city=models.CharField(max_length=100)
	marks=models.IntegerField()

	def __str__(self):
		return self.name

CBVProject/cbvapp/forms.py
from django import forms
from .models import Student

class StudentForm(forms.ModelForm):
	class Meta:
		model = Student
		fields ="__all__"

CBVProject/cbvapp/views.py
from django.shortcuts import render
from .forms import StudentForm
from .models import Student
from django.views.generic.edit import FormView,UpdateView,DeleteView
from django.views.generic.list import ListView
from django.views.generic.base import TemplateView
from django.urls import reverse_lazy


class HomePage(TemplateView):
	template_name='home.html'


class StudentFormView(FormView):
	form_class = StudentForm
	template_name = 'studentform.html'
	success_url = reverse_lazy('cbvapp:retrivedata')
	def form_valid(self, form):
		form.save()
		return super().form_valid(form)

class StudentListView(ListView):
	model = Student
	template_name='detail.html'

class StudentUpdateView(UpdateView):
    model = Student
    fields = '__all__'
    template_name='update.html'
    success_url = reverse_lazy('cbvapp:retrivedata')
class StudentDeleteView(DeleteView):
	model = Student
	template_name='delete.html'
	success_url = reverse_lazy('cbvapp:retrivedata')

CBVProject/cbvapp/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

    <title>CBV_crud</title>
  </head>
  <body>
    <h1 class="text-center">
      Class Based Views_crud
    </h1>

    
    {% block content %}
    {% endblock %}

 











   <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
    
  </body>
</html>

CBVProject/cbvapp/templates/delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}



{% block content %}
    <div class="container" style="width: 60%;">
        <form method="POST" class="jumbotron">
            {% csrf_token %}
            <h5>Are you sure to delete student with <b class="text-success">Roll No --> " {{object.rollno}} "</b> and <b class="text-danger">Name--> " {{object.name}} "</b></h5>
            <br>
            <input type="submit" value="Delete" class="btn btn-danger">
            <a href="{% url 'cbvapp:retrivedata' %}">
                <input type="button" value="Cancel" class="btn btn-dark" style="margin-left: 10%;">
            </a> 
        </form>
    </div>
    
{% endblock %}

CBVProject/cbvapp/templates/detail.html
{% extends 'base.html' %}


{% block content %}

    <div class="container mb-5">
    <h1 style="text-align: center;">Student Details</h1>
    <br><br>
        {% if object_list %}
            <table class="table table-striped table-hover">
                <tr class="thead-dark">
                    <th>RollNo</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>City</th>
                    <th>Marks</th>
                    <th>Update</th>
                    <th>Delete</th>
                </tr>
                {% for student in object_list %}
                    <tr>
                        <td>{{student.rollno}}</td>
                        <td>{{student.name}}</td>
                        <td>{{student.email}}</td>
                        <td>{{student.city}}</td>
                        <td>{{student.marks}}</td>
                        <td><a href="{% url 'cbvapp:update' student.id %}"><button class="btn btn-success">Update</button></a></td>
                        <td><a href="{% url 'cbvapp:delete' student.id %}"><button class="btn btn-danger">Delete</button></a></td>
                    </tr>
                {% endfor %}
            </table>
            <br>
            <a href="{% url 'cbvapp:studentform' %}">
                <button class="btn btn-primary">
                    Add Student
                </button>
            </a>
        {% else %}
            <h5>No records found,</h5>
            <br>
            <a href="{% url 'cbvapp:studentform' %}">
                <button class="btn btn-primary">
                    Add Student
                </button>
            </a>
        {% endif %}
    </div>


{% endblock %}

CBVProject/cbvapp/templates/home.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

    <title>CBV_crud</title>
  </head>
  <body>
    

   
 

<div class="container  mx-auto jumbotron mt-5">
  <h1 class="display-4 text-center">Class Based Views-->Crud Operations</h1>
  <div class="col-lg-4 mx-auto mt-3">
    <h2 text-center>1. Used Django forms</h2>
  
      <a class="btn btn-primary " href="{% url 'cbvapp:retrivedata' %}">Get All Details
      </a>
  </div>
  
</div>










   <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
    
  </body>
</html>

CBVProject/cbvapp/templates/studentform.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

 {% block content %}

    <div class="container">
        <h1 class="text-center">Student Form</h1>
            <form method="POST" class="col-lg-6 mx-auto mt-1 p-5" style="background-color: #f2d591" >
            {% csrf_token %}
            {{ form|crispy }}
           
            <input type="submit" value="Add Student" class="btn btn-success">
        </form>
     
    </div>

 {% endblock %}

CBVProject/cbvapp/templates/update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

 {% block content %}

    <div class="container">
        <h1 class="text-center">Student Form</h1>
            <form method="POST" class="col-lg-6 mx-auto mt-1 p-5" style="background-color: #f2d591" >
            {% csrf_token %}
            {{ form|crispy }}
           
            <input type="submit" value="Update" class="btn btn-success">
        </form>
     
    </div>

 {% endblock %}